### ISSUE TITLE
Add refresh button at bottom of page

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#1]

**Comment by VinitaPotter** [comment]
Can I do this?

**Comment by Ventrosky** [comment]
working on it

**Comment by pprathameshmore** [comment]
Add refresh button for change image

**Comment by pprathameshmore** [comment]
Look in the current version. There is a change image button in the left corner. Add refresh image button below author name

**Comment by pprathameshmore** [comment]
https://icons8.com/icons/set/refresh

**Comment by pprathameshmore** [comment]
![icons8-refresh-30](https://user-images.githubusercontent.com/17108186/66204144-c9cc4a80-e6c7-11e9-821f-af7ab3e2f2ef.png)

**Comment by pprathameshmore** [comment]
![icons8-refresh-30](https://user-images.githubusercontent.com/17108186/66204378-5e36ad00-e6c8-11e9-980b-ad2c0b73aa6e.png)
@Ventrosky Take look this icon

**Comment by pprathameshmore** [comment]
Just clone it on your machine.
Go to Chrome->Setting->More tools->Extension
Turn developer mode on
Select Load unpacked
Select cloned folder
Now Chrome Extension is installed in your Chrome.
Now make changes in code and reload that same extension from Chrome to see changes in the browser

**Comment by Ventrosky** [comment]
yep I'm doing some testing and ill open PR

**Comment by pprathameshmore** [comment]
There is a link in the left top corner, that changes the background image. Check whether that working or not? @Ventrosky

**Comment by Ventrosky** [comment]
added button on bottom of the page, added the icon in the folder, fixed small issue with fetchImage that didn't clear the div before appends; PR #6

**Comment by pprathameshmore** [comment]
Can you share a screenshot? Because I never tested your PR at locally. So I can merge it as soon as possible.

**Comment by Ventrosky** [comment]
![Refresh](https://user-images.githubusercontent.com/12787421/66210470-38a2a700-e6ba-11e9-9ef4-0cd6667324a0.PNG)

**Comment by pprathameshmore** [comment]
Can you put it below "See on Unsplash" text?

**Comment by pprathameshmore** [comment]
So I can merge it as soon as possible

**Comment by Ventrosky** [comment]
ok sure

**Comment by pprathameshmore** [comment]
Is that button working properly?

**Comment by pprathameshmore** [comment]
@Ventrosky Thank you for your contribution and for giving your valuable time to improving this project.

**Comment by Ventrosky** [comment]
thx to you for opening the hacktober fest issue , moved, closed old pull request and opnened a new one to avoid confusion

**Comment by pprathameshmore** [comment]
Yeah!

**Comment by pprathameshmore** [comment]
UI is a little bit shifted up. We have to keep centered the clock

**Comment by pprathameshmore** [comment]
No problem! Thank you again.

**Comment by pprathameshmore** [comment]
@Ventrosky If you don't mind. We can improve further like adding a to-do list feature.

**Comment by Ventrosky** [comment]
> @Ventrosky If you don't mind. We can improve further like adding a to-do list feature.

I can't sorry, got other tasks to solve, has been a pleasure, see you next time!

**Comment by pprathameshmore** [comment]
@Ventrosky Yeah!
