### ISSUE TITLE
Fix "Aw Snap" error

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#11]
After some minutes page doesn't display
![Annotation 2019-10-05 081146](https://user-images.githubusercontent.com/17108186/66248721-fd4eb980-e747-11e9-9a13-9c660528e64c.jpg)

**Comment by pprathameshmore** [comment]
@Tilak999 After your commit something is broken. Can you look at it?

**Comment by alejandrotoga02** [comment]
Is still the error ?
how can i replicate it ?

**Comment by rokibulislaam** [comment]
Well, I figured out the bug and making a PR #23 ! Reinstall the extension with the updated code to check the patch. Previously it was eating too much memory around 4GB and OS was forced to kill the process that's why it threw an **Aw Snap** error.

**Comment by pprathameshmore** [comment]
@rokibulislaam Thank you!
