### ISSUE TITLE
Fix p tag size

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#12]
Make p tag text size larger 
e.g. Build an API text in below image
![Annotation 2019-10-06 000723](https://user-images.githubusercontent.com/17108186/66259333-69bfcc00-e7cd-11e9-9493-dbeb7bb6525a.jpg)

**Comment by tombrowndev** [comment]
I'll do it!

**Comment by pprathameshmore** [comment]
@tombrowndev Go ahead!

**Comment by tombrowndev** [comment]
Created a PR for this issue: #13

**Comment by pprathameshmore** [comment]
Can you share screenshots? So I can confirm?

**Comment by tombrowndev** [comment]
![screenshot-127 0 0 1_5501-2019 10 05-20_07_02](https://user-images.githubusercontent.com/36549917/66259693-fbb6dd00-e7ab-11e9-9966-60e936e6d169.png)

**Comment by pprathameshmore** [comment]
@tombrowndev Thank you for your contribution and for giving your valuable time to improving this project.

**Comment by pprathameshmore** [comment]
@tombrowndev If you found any bug you can PR for that >

**Comment by pprathameshmore** [comment]
@tombrowndev Thank you again!
