### ISSUE TITLE
Make text size larger

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#14]
e.g. Make "What's in your mind" text in edit textbox a little bit larger. So easy to see.
![Annotation 2019-10-06 004456](https://user-images.githubusercontent.com/17108186/66259747-96c2ad80-e7d2-11e9-9d99-61dd76ddd433.jpg)

**Comment by thedeany** [comment]
I'll take this on!

**Comment by pprathameshmore** [comment]
Go ahead! @thedeany

**Comment by pprathameshmore** [comment]
Please share a screenshot so I can confirm and merge PR as soon as possible.

**Comment by thedeany** [comment]
This should do it. Let me know if this is alright, and I'll submit the PR.

![2019-10-05_1533](https://user-images.githubusercontent.com/4968754/66259898-8f28e780-e785-11e9-86c7-1e650101aba6.png)

I also noticed, as shown in the screenshot, the white text can be difficult to read when certain images are used as the background. My thought was to overlay a semi-opaque mask over the image or something similar. Should this be opened as a new issue?

**Comment by pprathameshmore** [comment]
Looks great! @thedeany
