### ISSUE TITLE
Reduce size of edit textbox

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#17]
See the size of the edit text box, so we have to reduce a little bit.
![Annotation 2019-10-06 011705](https://user-images.githubusercontent.com/17108186/66260054-20747a00-e7d7-11e9-8875-82466a5f71cb.jpg)

**Comment by AnBusse** [comment]
hey, I'd like to pick up this issue.

**Comment by Sumedhj16** [comment]
May I work on this issue?

**Comment by pprathameshmore** [comment]
@anbusse Go ahead!

**Comment by yordanzhelevdev** [comment]
I did it

**Comment by pprathameshmore** [comment]
Can you share a screenshot?
