### ISSUE TITLE
Add smooth transition to page

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#2]
Add smooth transition to the page, when reloads or first time opens.

**Comment by tilak999** [comment]
Can i take this task ?

**Comment by pprathameshmore** [comment]
Yeah @Tilak999

**Comment by pprathameshmore** [comment]
@Tilak999 Look at this animation in background https://chrome.google.com/webstore/detail/unsplash-instant/pejkokffkapolfffcgbmdmhdelanoaih?hl=en

**Comment by pprathameshmore** [comment]
Just clone it on your machine.
Go to Chrome->Setting->More tools->Extension
Turn developer mode on
Select Load unpacked
Select cloned folder
Now Chrome Extension is installed in your Chrome.
Now make changes in code and reload that same extension from Chrome to see changes in the browser

**Comment by tilak999** [comment]
okay, I am working on it, will open a pull request once done.

**Comment by pprathameshmore** [comment]
@Tilak999 Thank you for your contribution and for giving your valuable time to improving this project.
