### ISSUE TITLE
Fix issue related to cookies

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#25]
Detailed error
```A cookie associated with a cross-site resource at http://unsplash.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032. ```

**Comment by Doaa-Ismael** [comment]
Could I work in this?

**Comment by pprathameshmore** [comment]
Yeah @Doaa-Ismael

**Comment by Doaa-Ismael** [comment]
@pprathameshmore sorry but I can't reproduce it, how to do so?
And I found another error in console I will make a pull request with it

**Comment by pprathameshmore** [comment]
Yeah!
