### ISSUE TITLE
Fix issue with form

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#26]
When we try to insert blank value in the form, the form got hidden after blank value. Try to avoid getting hidden form.

**Comment by BarnikRay** [comment]
I want to work on this issue

**Comment by pprathameshmore** [comment]
@BarnikRay Go ahead! Please try post output of your changes in screenshot or videos.

**Comment by BarnikRay** [comment]
Sure!
