### ISSUE TITLE
Null value shows first time

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#3]
When you first time install this extension, there is "What is your main focus for today?" text below shows the "null" text. We have to show as "Click here to add"

**Comment by rowhitswami** [comment]
I'd like to take this up

**Comment by pprathameshmore** [comment]
@rowhitswami Yeah! Go ahead!

**Comment by rowhitswami** [comment]
Thank you @pprathameshmore 
Can you help me with setting up this project on my local machine? How can I test it on my machine?

**Comment by pprathameshmore** [comment]
Yeah!
1. Just clone it on your machine.
2. Go to Chrome->Setting->More tools->Extension
3. Turn developer mode on
4. Select Load unpacked
5. Select cloned folder
6. Now Chrome Extension is installed in your Chrome.

Now make changes in code and reload that same extension from Chrome to see changes in the browser.

![Annotation 2019-10-04 172818](https://user-images.githubusercontent.com/17108186/66206007-64c72380-e6cc-11e9-958b-fed1fe686a2b.jpg)

**Comment by rowhitswami** [comment]
Oh thank you so much but I figured it out and now I'm done with the code.
Raising PR in a few minutes. :blush:

**Comment by pprathameshmore** [comment]
We have to show as "Click here to add" when there is a null value

**Comment by rowhitswami** [comment]
Okay great. Let me work on it.
BTW found another bug. Creating an issue for the same.

**Comment by pprathameshmore** [comment]
Yeah! @rowhitswami

**Comment by pprathameshmore** [comment]
Did you see that there is a null value when you first time installed this extension? @rowhitswami

**Comment by rowhitswami** [comment]
Yeah, that's probably because it is creating p element but has no content to show in it. So I added a condition to check if it has a value or not.

**Comment by pprathameshmore** [comment]
Yeah! If there is no value then we have to show "Click here to add" message in p element.

**Comment by pprathameshmore** [comment]
@rowhitswami I never tested your PR at locally. Is that working properly so I can merge it?
