### ISSUE TITLE
Fix height issue!

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#30]
Sometime when using this extension on a 720px display, the page gets scrollbars. We have to keep the main page adaptive as per the screen.

**Comment by AhsanAyaz** [comment]
Gonna look at it.

**Comment by pprathameshmore** [comment]
@AhsanAyaz Yeah!

**Comment by joshuafbarker** [comment]
Looking at this as well. What is the desired behavior? Two columns? Smaller text?

**Comment by pprathameshmore** [comment]
When we open this extension on smaller screens. Quote and Change Background Button goes bottom of the page and we have to scroll down to see that. We have to keep responsive as per screens.

**Comment by joshuafbarker** [comment]
> When we open this extension on smaller screens. Quote and Change Background Button goes bottom of the page and we have to scroll down to see that. We have to keep responsive as per screens.

Right.. so on smaller screens, how do you want it to respond? Do you want the text to shrink to fit on the screen, do you want it to break into two columns, or would you like it to decrease the spacing between the items?

**Comment by pprathameshmore** [comment]
Yeah! We have to keep page responsive as a form factor. We know this extension gonna only works on Desktop, Laptop, and Tablet (No mobile)
