### ISSUE TITLE
Add names of contributors' in README.md file

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#31]
Add names of contributors' to this project.

**Comment by petr7555** [comment]
Please assign this to me

**Comment by pprathameshmore** [comment]
@petr7555 Go ahead!

**Comment by petr7555** [comment]
@pprathameshmore Done. https://github.com/pprathameshmore/Achieve-Chrome-Extension/pull/33

**Comment by pprathameshmore** [comment]
@petr7555 Put contributors' list on the top of license

**Comment by pprathameshmore** [comment]
@petr7555 Add your name too!

**Comment by petr7555** [comment]
@pprathameshmore Done. https://github.com/pprathameshmore/Achieve-Chrome-Extension/pull/37
