### ISSUE TITLE
Improve design of popup window

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#35]

**Comment by manojkrishnak** [comment]
Hi , can you plz give a little more description of the issue.

**Comment by sonya323** [comment]
Hi, can I work on this issue?

**Comment by pprathameshmore** [comment]
@manojkrishnak Look at the current popup window is not look as modern UI

**Comment by AniketOnWeb** [comment]
Hey pratham! Can i do some change in UI coz the font style and more stuff doesnt look much good.?

**Comment by pprathameshmore** [comment]
Only change popup page

**Comment by AniketChaudharyWeb** [comment]
> Only change popup page

u mean the main landing page?
