### ISSUE TITLE
Add URL of chrome ext on web

### ISSUE THREAD

**Issue by gurpreet-hanjra** [pprathameshmore/Achieve-Chrome-Extension#36]
Hello. For some reason, I was not able to find this on https://chrome.google.com/webstore/search/achieve?_category=extensions 

Would be great if we can add the url on readme.md to view it

**Comment by pprathameshmore** [comment]
@gurpreet-hanjra Due to some payment issue I not able to upload this extension on Chrome Web Store. Soon I will upload to Chrome Web Store.

**Comment by gurpreet-hanjra** [comment]
Ah okay, please let me know if I can help. Thank you.

**Comment by pprathameshmore** [comment]
@gurpreet-hanjra Can you give me your LinkedIn profile link. I have some queries regarding to career guidance.
