### ISSUE TITLE
Add demo video link in README file

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#39]
https://www.youtube.com/watch?v=lZZXsh_7trY

**Comment by geektutor** [comment]
Picking up this issue

**Comment by Yatharth4599** [comment]
picking up this issue

**Comment by pprathameshmore** [comment]
@Yatharth4599 Go ahead.

**Comment by Yatharth4599** [comment]
Please can you make me a contributor as i cannot push the changes

**Comment by Yatharth4599** [comment]
@pprathameshmore

**Comment by Yatharth4599** [comment]
@pprathameshmore please can you grant the contributor access

**Comment by igor-nm** [comment]
I'll do some update to put a reference on README.MD
