### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#42]
Give contributors issue templates that help you cut through the noise and help them push your project forward.

**Comment by JacobMGEvans** [comment]
Only people with collaborator access can do this. It probably shouldn't have the hacktoberfest label being a restricted access type settings issue.

**Comment by JacobMGEvans** [comment]
Official GitHub walkthrough on how to setup templates though.
https://help.github.com/en/articles/creating-issue-templates-for-your-repository
