### ISSUE TITLE
Create icon for extension

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#44]
Create a simple and cool looking icon. In three different size 16px, 32px and 64px.

**Comment by ploh007** [comment]
Is the desired outcome to improve upon the current icon (i.e. keep the summit idea) or are you open to a complete redesign?

**Comment by pprathameshmore** [comment]
Complete redesign the logo

**Comment by ploh007** [comment]
Here are some ideas. 

![Logo_1](https://user-images.githubusercontent.com/16789433/66429468-15dbff80-e9e6-11e9-9667-e81ba55ce6ca.png) ![Logo_2](https://user-images.githubusercontent.com/16789433/66429469-15dbff80-e9e6-11e9-9887-56a5608303ef.png)

**Comment by pprathameshmore** [comment]
Second one looks good!

**Comment by pprathameshmore** [comment]
We can use that.

**Comment by ploh007** [comment]
Created a pull request for the updates to the icons.

**Comment by pprathameshmore** [comment]
@ploh007 Done!
