### ISSUE TITLE
Quotes, credits and location are not visible

### ISSUE THREAD

**Issue by rowhitswami** [pprathameshmore/Achieve-Chrome-Extension#5]
![Screenshot from 2019-10-04 17-52-44](https://user-images.githubusercontent.com/16516296/66207341-29c6ef00-e6d0-11e9-9cad-244f2bb41244.png)

**Comment by pprathameshmore** [comment]
Can you upload a full screenshot?

**Comment by pprathameshmore** [comment]
![Annotation 2019-10-04 175859](https://user-images.githubusercontent.com/17108186/66207545-ab1e8180-e6d0-11e9-9c99-673081ab491c.jpg)

**Comment by rowhitswami** [comment]
![Screenshot from 2019-10-04 18-21-08](https://user-images.githubusercontent.com/16516296/66208889-dbb3ea80-e6d3-11e9-9dda-d33caad54050.png)

**Comment by pprathameshmore** [comment]
Click on Change Image link

**Comment by pprathameshmore** [comment]
So you will see Photo's author

**Comment by rowhitswami** [comment]
Still not working

**Comment by pprathameshmore** [comment]
May be API has a limit of 50 requests/ hrs. That's why it is not working. Try again after some time.

**Comment by rowhitswami** [comment]
Great. No issues.

**Comment by pprathameshmore** [comment]
@rowhitswami I never tested your PR at locally. Is that working properly so I can merge it?

**Comment by pprathameshmore** [comment]
Maybe this does not issue! We can close it!

**Comment by rowhitswami** [comment]
Yes, that **Click here to add** thing is working fine.
Reopening this issue, because when I resize the window I can see the information.

![Screenshot from 2019-10-04 18-40-42](https://user-images.githubusercontent.com/16516296/66210139-bd9bb980-e6d6-11e9-8ad5-caa8a0c6fc29.png)

**Comment by pprathameshmore** [comment]
@rowhitswami Thank you for your contribution and for giving your valuable time to improving this project.

**Comment by rowhitswami** [comment]
@pprathameshmore I'm on it

**Comment by pprathameshmore** [comment]
I would like to connect with you! If you don't mind.

**Comment by rowhitswami** [comment]
Sure, we can connect on LinkedIn: https://www.linkedin.com/in/rowhitswami
