### ISSUE TITLE
Replace old API by QuoteGarden API

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#52]
**Describe the bug**
Currently in use API is from freecodecamp.org. I have developed my own API. Which contains more than 5000 quotes. We have to use this API.

**Expected behavior**
New Quotes with new API

**Additional reference**
https://pprathameshmore.github.io/QuoteGarden/
https://github.com/pprathameshmore/Achieve-Chrome-Extension/blob/e7b569b4f6b9e6323716b05625c2ef934884db84/static/scripts/main.js#L156

**Comment by rmasianjr** [comment]
Hi sir.. i want to help, can you assign me to this?. thanks :)

**Comment by maloney8** [comment]
Hey, I'd like to do on this one. May I?
