### ISSUE TITLE
Set 3 minutes time interval so background image will change automatically

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#53]
**Is your feature request related to a problem? Please describe.**
Currently, the background image changed manually by user.

**Describe the solution you'd like**
Set 3 minutes time interval so the background image will change automatically.
We have to keep the existing manual option too.

**Additional context**
Don't break existing features.

**Comment by dnafication** [comment]
I am having a look at this one :)
Should we use something simple like setInterval?

**Comment by adityakmr7** [comment]
I made a PR fixing this issue have a look.

**Comment by dnafication** [comment]
Okay.. let me pull it in and review if it works
