### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#56]
**Describe the bug**
Uncaught (in promise) TypeError: Failed to fetch

**Expected behavior**
Fix issue

**Screenshots**
![Annotation 2019-10-11 092826](https://user-images.githubusercontent.com/17108186/66623483-80b95080-ec09-11e9-8982-6f39488bedab.jpg)

**Additional context**
Don't break the existing code.

**Comment by rmasianjr** [comment]
Hi...maybe your frontend and backend running in different origin..For security reasons, browsers restrict cross-origin HTTP requests..To fix it, try to enable/allow cors in your backend.. Thanks..

**Comment by yohan-choi-dev** [comment]
If you don't mind, I will try to fix it

**Comment by pprathameshmore** [comment]
@cyh0968 Go ahead.

**Comment by Aleksandar15** [comment]
@pprathameshmore seem like he fixed it?

**Comment by pprathameshmore** [comment]
Yes

**Comment by shrutimkrishnan** [comment]
@cyh0968 how did you fix it?

**Comment by pprathameshmore** [comment]
@shrutimkrishnan If not fixed then you can work on this issue.
