### ISSUE TITLE
Center the placeholder text in the input box.

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#67]
**Describe the bug**
Center the placeholder text in the input box.

**Screenshots**

![image](https://user-images.githubusercontent.com/17108186/94434350-4698e400-01b7-11eb-8ea1-aa3f408d86f3.png)

**Comment by rishavjaiss** [comment]
Hi, I'll do this! Assign this to me if you want, I will make pr on or after 1st Oct during hacktoberfest.

**Comment by Gautam-Arora24** [comment]
Can I solve this issue?
