### ISSUE TITLE
Remove scrollbar from page

### ISSUE THREAD

**Issue by pprathameshmore** [pprathameshmore/Achieve-Chrome-Extension#70]
**Describe the bug**
Remove the scrollbar from the extension homepage. Keep responsive to the display size.

**Expected behavior**
Extension page without scrollbars

**Screenshots**
![image](https://user-images.githubusercontent.com/17108186/94885751-ad0b5400-048e-11eb-9274-a61daf539a7f.png)

**Comment by casalazara** [comment]
I can help you!

**Comment by pprathameshmore** [comment]
@casalazara Go ahead.

**Comment by pprathameshmore** [comment]
@casalazara You broke other design

**Comment by casalazara** [comment]
Which one?

**Comment by MabiGermano** [comment]
Can I do it for you?

**Comment by pprathameshmore** [comment]
@MabiGermano Go ahead.

**Comment by IamODJ** [comment]
Do you want to remove only horizontal scrollbar or both horizontal and vertical?

**Comment by IamODJ** [comment]
I have figured out how to fix it, Could you please assign it to me?

**Comment by pprathameshmore** [comment]
> Do you want to remove only horizontal scrollbar or both horizontal and vertical?

Yes

**Comment by MabiGermano** [comment]
I PR. 
If it wasn't that you expected, please, let me know.

**Comment by pprathameshmore** [comment]
@MabiGermano Sure

**Comment by glauroqj** [comment]
hello @pprathameshmore  that problem was already solved?
